name: manual test
on:
  workflow_dispatch:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: RUn my action
        id: custom_action
        uses: actions/repo-permission-check@v0.1.0-alpha.0
      - run: echo ${{ steps.custom_action.outputs.authorized }}
