name: manual test
on:
  workflow_dispatch:
  push:
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: RUn my action
        id: custom_action
        uses: zjutszl/repo-permission-check@v0.1.0-alpha.0
      - name: print
        if: steps.custom_action.outputs.authorized != 'true'
        run: echo success
