name: refuse modify specific files
on: [pull_request_target]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify Changed files
        uses: tj-actions/verify-changed-files@v5.4
        id: changed_files
        with:
          files: |
             .github/workflow/.(yaml|yml)
      - name: check permission when files change
        id: permission_check
        if: steps.changed_files.outputs.files_changed == 'true'
        uses: "lannonbr/repo-permission-check-action@2.0.0"
        with:
         permission: "write"
      - name: echo output
        run: echo ${{ steps.permission_check.outputs.pass == 'true' }}
      - uses: superbrothers/close-pull-request@v3
        if: steps.permission_check.output.pass == 'true'
        with:
          # Optional. Post a issue comment just before closing a pull request.
          comment: "We do not accept PR which would changes our workflows. "
